name: fleabay-dev
channels:
  - conda-forge
dependencies:
  - python=2.7
  - pytest
  - pep8
  - autopep8
  - ipython
  - click
  - pysocks
  - beautifulsoup4
  - psycopg2
  - pip
  - pip:
    - git+https://github.com/timotheus/ebaysdk-python.git
  - sqlalchemy
  - pandas
